In [5]:
lst=[[5,6,7],[8,3,3],[4,5,9]]

In [6]:
dic={}

In [7]:
for i in range(len(lst)):
    dic[i+1]=lst[i]
print(dic)

{1: [5, 6, 7], 2: [8, 3, 3], 3: [4, 5, 9]}


In [29]:
dic1={}
for i in range(len(lst)):
    l=[]
    for j in range(len(lst[i])):
      l.append(lst[j][i])
    dic1[i+1]=l
print(dic1)
    

{1: [5, 8, 4], 2: [6, 3, 5], 3: [7, 3, 9]}


In [48]:
s1=input()
s2=input()
S1=''
for i in s1:
    if i not in S1:
        S1+=i
S2=''
for i in s2:
    if i not in S2:
        S2+=i
lst=[]
for j in S1:
    if j in S2:
        lst.append(j)
ans1=''
ans2=''
ls1=[]
ls2=[]
for k in lst:
    x=S1.index(k)
    y=S2.index(k)
    ans1=S1[0:x]+k+S2[y+1:]
    ans2=S2[0:y]+k+S1[x+1:]
    ls1.append(ans1)
    ls2.append(ans2)
Lst=ls1+ls2
Lst.sort()
for j in Lst:
    print(j)
  
    


abcdce
ecfgdc
abcd
abcdecfgd
abcfgd
e
ecde
ecfgde


In [2]:
n=int(input())
lst=[]
for i in range(n):
    x=int(input())
    lst.append(x)

L=[]
for i in range(1,n+1):
    s=0
    l=[]
    for j in range(i):
        s+=lst[j]
        l.append(lst[j])
    avg=s/len(l)
    L.append(avg)
S=0
for i in L:
    S+=i
    Avg=S/len(L)
print("{:0.2f}".format(Avg))    
    
    
        

4
1
7
8
9
4.15


In [10]:
import random
S1=input()
S2=input()
L1=list(S1)
L2=list(S2)
set1=set(L1)
set2=set(S2)
Set=set1.symmetric_difference(set2)
lst_final=list(Set)

print(''.join(lst_final))

aacdb
gafd
fgcb


In [6]:
import math
h=int(input())
up_P=int(input())
straight_P=int(input())
down_P=int(input())
s1=int(input())
s2=int(input())
s3=int(input())
s4=int(input())
s5=int(input())
Time=h/s4+h/s5+2*(up_P/s1+straight_P/s3+down_P/s2)
x=Time/60
t=math.modf(x)
print(int(t[1]),math.ceil(t[0]*100),sep=' ')

230
170
310
217
6
12
11
7
8
3 52


In [1]:
print(2*(170/6+310/11+217/12))

149.1969696969697


In [22]:
lst=[1, 3, 5, 1, 3, 2, 5, 4, 2]
L=[]
Set=set(lst)
for i in Set:
    a=[]
    for j in range(lst.count(i)):
        a.append(i)
    L.append(a)
print(L)




[[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [7]:
r1=int(input())
c1=int(input())
M1=[]
for i in range(r1):
    x=list(map(int,input().split()))
    M1.append(x)
r2=int(input())
c2=int(input())
M2=[]
for i in range(r2):
    y=list(map(int,input().split()))
    M2.append(y)

M3=M1
for i in range(len(M1)):
    for j in range(len(M1[i])):
        for k in M2:
            if M1[i][j] in k:
                M3[i][j]=0
for row in M3:
    for k in row:
        print(k,end=' ')
    print()


3
3
4 5 7
1 9 11
12 3 2
2
2
15 5 
11 2
4 0 7 
1 9 0 
12 3 0 


In [16]:
n=int(input())
cute=[]
i=1
while len(str(i))<=len(str(n)):
    if '0' not in str(i) and '1' not in str(i) and '2' not in str(i) and '3' not in str(i) and '4' not in str(i) and '5' not in str(i) and '6' not in str(i) and '7' not in str(i):
        cute.append(i)
    i+=1


for j in cute:
    if n%j==0:
        print('beautiful')
        break
    elif n%j!=0 and cute.index(j)==len(cute)-1:
        print(-1)
        break

10668
beautiful


In [26]:
import itertools
n=int(input())
cute=[]
for i in range(1,len(str(n))+1):
    for j in list(itertools.product('89',repeat=i)):
        cute.append(int(''.join(j)))

for j in cute:
    if n%j==0:
        print('beautiful')
        break
    elif n%j!=0 and cute.index(j)==len(cute)-1:
        print(-1)
        break

10668
beautiful


In [27]:
import itertools
n=int(input())
ans=-1
for i in range(1,len(str(n))+1):
    for j in [int(''.join(k)) for k in list(itertools.product('89',repeat=i))]:
        if n%j==0:
            ans='beautiful'
            break
print(ans)

10668
beautiful


In [20]:
T=int(input())
lst=[]
for i in range(T):
    x=input().lower()
    lst.append(x)

for ele in lst:
    if len(ele)%2==0:
        a=ele[0:len(ele)//2]
        b=ele[len(ele)//2:]
        ans='YES'
        for i in a:
            if i not in b:
                ans='NO'
                break
            else:
                if a.count(i)==b.count(i):
                    ans='YES'
                else:
                    ans='NO'
    else:
        a=ele[0:len(ele)//2]
        b=ele[len(ele)//2+1:]
        ans='YES'
        for i in a:
            if i not in b:
                ans='NO'
                break
            else:
                if a.count(i)==b.count(i):
                    ans='YES'
                else:
                    ans='NO'
    print(ans)
            
        

1
abbaab
NO


In [23]:
x='abcdabe'
print(sorted(x[0:len(x)//2]))

['a', 'b', 'c']


In [7]:
T=int(input())
lst=[]
for i in range(T):
    x=input().lower()
    lst.append(x)

for ele in lst:
    n=len(ele)//2
    a=sorted(ele[0:n])
    b=sorted(ele[-n:])
    if a==b:
        print('YES')
    else:
        print('NO')

1
rotor
YES


In [9]:
import itertools
S=input()
lst=[]
for i,j in itertools.groupby(S):
    lst.append({i:list(j)})

for row in lst:
    for l in row:
        print((row[l].count(l),int(l)),end=' ')
    

1222311
(1, 1) (3, 2) (1, 3) (2, 1) 

In [13]:
for i in range(1,int(input())+1):
    print((((10**i)-1)//9)**2)

5
1
121
12321
1234321
123454321


In [4]:
import collections
x=[1,1,2,2,3,3,3,4,4,4,5,6,7]
print(collections.Counter(x))

Counter({3: 3, 4: 3, 1: 2, 2: 2, 5: 1, 6: 1, 7: 1})


In [15]:
IM=list(map(int,input().split()))
Dragon=[]
for i in range(IM[1]):
    row=list(map(int,input().split()))
    Dragon.append([row[0],row[1]])
Dragon.sort()
ans='YES'
while len(Dragon)>0:
    x=Dragon.pop(0)
    if IM[0]<x[0]:
        ans='NO'
        break
    elif IM[0]>x[0]:
        IM[0]+=x[1]
        ans='YES'
print(ans)
    


    

    
            
        
    

8 1
100 10
NO


In [35]:
import re
x='color: #FFFFFF; font-size:123px; background-color: #abc;'
print(re.findall('#{1}[0-9 or A-F or a-f]{3,6}',x))


['#FFFFFF', '#abc']


In [37]:
import re
N=int(input())
lst=[]
for i in range(N):
    line=input()
    lst.append(line)
    
for line in lst:
    if re.match('#',line):
        continue
    else:
        x=re.findall('#{1}[0-9 or A-F or a-f]{3,6}',line)
        for i in x:
            print(i)

4
#ABC
{
  color: #FFFFFF; font-size:123px; background-color: #abc;'
}
#FFFFFF
#abc


In [50]:
import re
N=int(input())
ans='Invalid'
lst=[]
for i in range(N):
    x=input()
    lst.append(x)

for j in lst:
    if re.match('[4-6]{1}[0-9]{15}$',j) or re.match('[4-6]{1}[0-9]{3}-[0-9]{4}-[0-9]{4}-[0-9]{4}$',j):
        if re.search()
        
        
    else:
        ans='Invalid'
    print(ans)

3
4567890123456789
5678-1234-7890-1357
1029384756293847
Valid
Valid
Invalid


In [73]:
n=int(input())
a=0
b=1
lst=[]
lst.append(a)
lst.append(b)
for i in range(n-2):
    c=a+b
    a,b=b,c
    lst.append(c)
print(lst)

5
[0, 1, 1, 2, 3]


In [80]:
def fibonacci(n):
    if n!=1 and n!=0:
        a=0
        b=1
        lst=[]
        lst.append(a)
        lst.append(b)
        for i in range(n-2):
            c=a+b
            a,b=b,c
            lst.append(c)
        return lst
    elif n==0:
        return []
    elif n==1:
        return [0]

cube=lambda x:x**3
print(list(map(cube,fibonacci(0))))


[]


In [88]:

N=int(input())
n=str(N)
x=[]
if n[0]!='9':
    if 9-int(n[0])<int(n[0]):
        x.append(str(9-int(n[0])))
    else:
        x.append(n[0])
    
    for i in n[1:]:
        if 9-int(i)<int(i):
            x.append(str(9-int(i)))
        else:
            x.append(i)

else:
    x.append('9')
    for i in n[1:]:
        if 9-int(i)<int(i):
            x.append(str(9-int(i)))
        else:
            x.append(i)
print(''.join(x))
    
    
        

4567890
4432100


In [6]:
import numpy
lst=[2,4,6,8,10,12,14,16,18]
arr=numpy.array(lst)
print(numpy.reshape(arr,(3,3)))
x=numpy.reshape(arr,(3,3))
print(numpy.transpose(x))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


In [29]:
import textwrap
def merge_the_tools(string, k):
    
    lst=textwrap.wrap(string,k)
    L=[]
    for ele in lst:
        x=''
        for j in ele:
            if j not in x:
                x+=j
        L.append(x)
    
    for word in L:
        print(word)
    return ' '

string=input()
k=int(input())
print(merge_the_tools(string,k))

abcdefgh
3
abc
def
gh
 


In [82]:
import collections
s=input()
chr_count=collections.Counter(s)
sorted_chr_count=sorted(chr_count.items())
sorted_reverse=sorted(sorted_chr_count,reverse=True,key=lambda x:x[1])

for i in range(3):
    print(sorted_reverse[i][0],sorted_reverse[i][1])


aabbcccde
c 3
a 2
b 2


In [99]:
n=input()
list1=n.split(' ')
for i in list1:
    print(i.capitalize(),end=' ')

132 456 Wq  m e
132 456 Wq  M E 

In [100]:
import functools
s=input()
lst=[]
L=list(s)

for i in range(len(L)):
        lst.append(s[i:]+s[:i])
x=set(lst)
print(len(x))   


aacd
['aacd', 'acda', 'cdaa', 'daac']
{'aacd', 'acda', 'cdaa', 'daac'}


In [2]:
n=int(input())
groups=list(map(int,input().split()))
cabs=0
groups.sort()

while len(groups)>1:
    Sum=groups[0]+groups[-1]
    if Sum==4:
        groups.pop(0)
        groups.pop(-1)
        cabs+=1
    elif Sum>4:
        groups.pop(-1)
        cabs+=1
    else:
        groups.append(groups.pop(0)+groups.pop(-1))
if len(groups)>0:
    cabs+=1
print(cabs)
                

5
2 3 3 2 1
3


In [14]:
print(ord('a'))
print(ord('b'))
print(ord('c'))
print(ord('x'))
print(ord('y'))
print(ord('z'))

97
98
99
120
121
122


In [16]:
s=input()
ch=input()
ch_count=s.count(ch)
if ch_count==0:
    print('No')
else:
    Sum=0
    for i in range(len(s)):
        if s[i]==ch:
            Sum+=i
if ch_count%2==0 and Sum%2==0:
    print('even-even')
elif ch_count%2==0 and Sum%2!=0:
    print('even-odd')
elif ch_count%2!=0 and Sum%2!=0:
    print('odd-odd')
elif ch_count%2!=0 and Sum%2==0:
    print('odd-even')    
    
    
        

elephant
z
No


In [10]:
S1=input()
S2=input()
n=int(input())
lst1=list(S1)
lst2=list(S2)
L=[]
L.append(S1)
L.append(S2)


for i in range(n-2):
    lst3=[]
    for j in range(len(S1)):
        if (j+1)%2==0:
            if lst2[j]=='z':
                lst3.insert(j,'a')
            else:
                lst3.append(chr(ord(lst2[j])+1))
        elif (j+1)%2!=0:
            
            if lst1[j]=='z':
                lst3.insert(j,'a')
            else:
                lst3.append(chr(ord(lst1[j])+1))
    lst1,lst2=lst2,lst3
    L.append(''.join(lst3))

print(L[-1])
    
    
    

10
amey
dhft
['amey', 'dhft', 'bifu', 'ejgv', 'ckgw', 'flhx', 'dmhy', 'gniz', 'eoia{', 'hpjb']
hpjb


In [ ]:
w=input()
pre_partners=[]
for i in range(97,110):
    pre_partners.append(chr(i))

mid=len(w)//2
ans='Lost'
for i,j in list(enumerate(w[0:mid])):
    if j in pre_partners:
        c=chr(ord(j)+13)
        if w[i+1]==c 



In [21]:
print(list(enumerate('abcde')))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]


In [22]:
T=int(input())
for i in range(T):
    k=int(input())


2


In [23]:
T=int(input())
lst=[]
for i in range(T):
    N=int(input())
    lst.append(N)

for i in range(len(lst)):
    a=1
    fact=1
    while a<=lst[i]:
        fact*=a
        a+=1
    print(fact)

3
4
5
6
24
120
720


In [2]:
n=int(input())
matrix=[]
for i in range(n):
    row=list(map(int,input().split()))
    matrix.append(row)
for i in matrix:
    i.sort()
    
S=[]
for j in matrix:
    S+=j
    
S.sort()
print(S)


1

[]


In [6]:
import itertools
import numpy
T=int(input())
for i in range(T):
    n=int(input())
    pts=list(map(int,input().split()))

    



1
3
2 4 5
[(2, 4), (2, 5), (4, 5)]


In [8]:
print(list(itertools.combinations([2,1,4],2)))

[(2, 1), (2, 4), (1, 4)]


In [38]:
dim=list(map(int,input().split()))
matrix=[]
for i in range(dim[0]):
        row=[]
        for j in range(dim[1]*i+1,dim[1]*i+dim[1]+1):
            row.append(j)
        matrix.append(row)
for row in matrix:
    for k in row:
        print(k,end=' ')
    print()
            
    

3 3
1 2 3 
4 5 6 
7 8 9 


In [32]:
n=int(input())
matrix=[]
for i in range(n):
    row=list(map(int,input().split()))
    matrix.append(row)
a=0
b=0
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        if matrix[i][j]==matrix[j][i]:
            a=1
        elif matrix[i][j]==-matrix[j][i]:
            a=2
            break

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        if matrix[i][j]==-matrix[j][i]:
            b=1
        elif matrix[i][j]!=-matrix[j][i]:
            b=2
            break
            
if a==1:
    print('symmtric')
elif b==1:
    print('skew-symmtric')
elif a==2 and b==2:
    print('neither')


3
0 2 3
-2 0 8
-3 -8 0
skew-symmtric


In [7]:
import itertools
d=input()
k=int(input())
x=list(itertools.combinations(d,k))
lst=[]
for i in x:
    lst.append(''.join(i))
lst.sort()
for dna in lst:
    print(dna)


ccag
3
cag
cag
cca
ccg


In [13]:
import itertools
value=list(map(str,input().split()))
L=list(value[0])
L.sort()
val=''.join(L)
lst=[''.join(i) for i in list(itertools.combinations_with_replacement(val,int(value[1])))]
for i in lst:
    print(i)

HACK 2
AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [18]:
import itertools
N=int(input())
letters=list(map(str,input().split()))
K=int(input())
lst=[]
for i in range(len(letters)):
    lst.append(i+1)
lst_final=list(itertools.combinations(lst,K))
l1=[]
for i in range(len(letters)):
    if letters[i]=='a':
        l1.append(i+1)
l2=[]
for x in l1:
    for ele in lst_final:
        if x in ele:
            l2.append(ele)
Set=set(l2)
prob=len(Set)/len(lst_final)
print('{:0.4f}'.format(prob))


4
a a c d
2
0.8333


In [26]:
import copy
m=int(input())
n=int(input())
p=int(input())
q=int(input())
matrix=[]
for i in range(m):
    kids=list(map(int,input().split()))
    matrix.append(kids)
l=int(input())
matrix_final=copy.deepcopy(matrix)
if l==p:
    for i in range(m):
        for j in range(len(matrix[i])):
            column=[matrix[a][j] for a in range(m)]
            if matrix[i][j]==p:
                if q in matrix[i] or q in column:
                    matrix_final[i][j]=q
                else:
                    matrix_final[i][j]=p
            
elif l==q:
    for i in range(m):
        for j in range(len(matrix[i])):
            column=[matrix[a][j] for a in range(m)]
            if matrix[i][j]==q:
                if p in matrix[i] or p in column:
                    matrix_final[i][j]=p
                else:
                    matrix_final[i][j]=q
           
            
        
winners=[]
for i in range(m):
    for j in range(len(matrix_final[i])):
        if matrix_final[i][j]==l:
            winners.append((i+1,j+1))
if len(winners)>0:
    for x in winners:
        print(x[0],x[1])
else:
    print('No winner')
        

3
3
3
5
3 5 3
3 3 3
3 5 5
3
2 1


In [9]:
n=int(input())
def func(x):
    l=[]
    for i in range(1,x+1):
        if x%i==0:
            l.append(i)
    return l

dic={}
lst=[]
a=1
lst.append(a)
for i in range(2,n+1):
    c=a+i
    a=c
    lst.append(c)
for k in lst:
    dic[k]=func(k)
    
print(dic)    

5
{1: [1], 3: [1, 3], 6: [1, 2, 3, 6], 10: [1, 2, 5, 10], 15: [1, 3, 5, 15]}


In [20]:
n=int(input())
pipes=[]
for i in range(n):
    l=int(input())
    pipes.append(l)
pipes.sort()
cost=0
while len(pipes)>1:
    pipe1=pipes.pop(0)
    pipe2=pipes.pop(0)
    cost+=(pipe1+pipe2)
    pipes.append(pipe1+pipe2)

if n>1:
    print(cost)
else:
    print(pipes[0])
    

    

    


3
1
2
3
9


In [1]:
import queue
n=int(input())
pipes=queue.PriorityQueue()
for i in range(n):
    pipes.put(int(input()))
cost=0
while pipes.qsize()>1:
    pipe1=pipes.get()
    pipe2=pipes.get()
    cost+=(pipe1+pipe2)
    pipes.put(pipe1+pipe2)

print(cost)

5
2
4
3
1
5
33


In [29]:
x=list(map(int,input().split()))

d=int(input())
def rotate1(lst):
    copied=lst.copy()
    temp=lst[0]
    for i in range(len(copied)-1):
        copied[i]=copied[i+1]
    copied[len(lst)-1]=temp
    return copied

for i in range(d):
    a=rotate1(x)
    x=a
print(x)
    


    

1 2 3 4 5
2
[3, 4, 5, 1, 2]


In [7]:
n=int(input())
superdic={}
for i in range(n):
    dic={}
    taxonomy=input()
    level1=list(map(str,input().split()))
    for j in range(len(level1)):
        level2=list(map(str,input().split()))
        dic[level1[j]]=level2
    superdic[taxonomy]=dic
p=input()
l1=input()
l2=input()
if p in superdic.keys()
        if l1 in superdic[p]:
            if l2 in superdic[p][l1]:
                print('Taxonomy present')
            else:
                print('Taxonomy not present')
                
        else:
            print('Taxonomy not present')
            
    else:
        print('Taxonomy not present')
        
    
        

2
veggies
pulses roots greens
pulses beans peas
None
greens cabbage spinach
colors
purple red green
purple lavender violet
None
None
veggies
greens
spinach
Taxonomy present


In [ ]:
n=int(input())
total=0
store={}
for i in range(n):
    word=input()
    time=0
    if word in store:
        time=store[word]//2
    else:
        for j in range(len(word)):
            if j==0:
                time+=2
            else:
                if (word[j-1] in 'df' and word[j] not in 'df') or (word[j-1] in 'jk' and word[j] not in 'jk'):
                    time+=2
                else:
                    time+=4
        store[word]=time
    total+=time
print(total)

In [1]:
customers=[]
for i in range(20):
    customers.append(input())
lst=[]
Set=set(customers)
for co in Set:
    if (customers.count(co)/len(customers))*100>=5:
        lst.append(co)
lst.sort()
for i in lst:
    print(i)

alpha
omega
alpha
omega
alpha
omega
alpha
omega
alpha
omega
alpha
omega
alpha
omega
alpha
alpha
omega
alpha
omega
beta
alpha
beta
omega


In [10]:
N=int(input())
dic={'src':[],'des':[]}
for i in range(N):
    x=list(map(str,input().split()))
    dic['src'].append(x[0])
    dic['des'].append(x[1])
print(dic)

    


        


    

3
del kol
maa del
kol goa
{'src': ['del', 'maa', 'kol'], 'des': ['kol', 'del', 'goa']}


In [13]:
n=int(input())
b=int(input())
s=str(n)
ans=True
for i in s:
    if int(i)>(b-1):
        ans=False
        break
if ans==True:
    S=0
    for i in s:
        S+=(int(i)**len(s))
    lst=[]
    for i in range(len(s)):
        x=S//b
        lst.append(str(S%b))
        S=x
    lst.reverse()
    if ''.join(lst)==s:
        print('Yes')
    else:
        print('No')
else:
    print('Invalid')

435
5
Invalid


In [3]:
x=input()
lst=x.split(' ')
for i in lst:
    print(i.capitalize(),end=' ')
        
    

alan 12abd hack
Alan 12abd Hack 

In [6]:
n=int(input())
tickets=[input().split() for i in range(n)]
itenary=[]
c=0
while len(itenary)<n+1:
    for ele in tickets:
        if c==0:
            itenary+=ele
            c=-1
            tickets.remove(ele)
        elif ele[0]==itenary[-1]:
            itenary.append(ele[1])
            tickets.remove(ele)
        elif ele[1]==itenary[0]:
            itenary.insert(0,ele[0])
            tickets.remove(ele)
print(*itenary)

3
del kol
maa del
kol goa
maa del kol goa


In [18]:
print('My name is Rishi'.endswith('shi'))

True


In [12]:
n1=int(input())
l1=[]
for i in range(n1):
    l1.append(int(input()))
n2=int(input())
l2=[]
for i in range(n2):
    l2.append(int(input()))

l3=[]
if n2<n1:
    sub_l1=l1[n2:]
    for i in range(n2):
        if l1[i]%(i+1)==0:
            if l2[i]%(i+1)==0:
                l3.append(l1[i])
                l3.append(l2[i])
            else:
                l3.append(l1[i])
        elif l1[i]%(i+1)!=0:
            if l2[i]%(i+1)==0:
                 l3.append(l2[i])
            
                
       
    for j in range(len(sub_l1)):
        if sub_l1[j]%(l1.index(sub_l1[j])+1)==0:
            l3.append(sub_l1[j])
elif n1<n2:
      sub_l2=l2[n1:]
      for i in range(n1):
        if l2[i]%(i+1)==0:
            if l1[i]%(i+1)==0:
                l3.append(l1[i])
                l3.append(l2[i])
            else:
                l3.append(l2[i])
        elif l2[i]%(i+1)!=0:
            if l1[i]%(i+1)==0:
                 l3.append(l1[i])
            
      for j in range(len(sub_l2)):
        if sub_l2[j]%(l2.index(sub_l2[j])+1)==0:
            l3.append(sub_l2[j])
else:
     
    for i in range(n2):
        if l1[i]%(i+1)==0:
            l3.append(l1[i])
            if l2[i]%(i+1)==0:
                l3.append(l2[i])
        elif l1[i]%(i+1)==0 and l2[i]%(i+1)==0:
            l3.append(l1[i])
            l3.append(l2[i])


for k in range(len(l3)):
    if l3[k]%(k+1)==0:
        print(l3[k],sep=' ')
        

6
15
12
17
32
26
42
4
45
34
64
80
[15, 45, 12, 34, 32, 80, 42]
15 12 42 

In [4]:
n=int(input())
pts=list(map(int,input().split()))
up=1
down=0
for i in range(1,len(pts)-1):
    if pts[i+1]<pts[i]>pts[i-1]:
        down+=1
    elif pts[i+1]>pts[i]<pts[i-1]:
        up+=1
print(up,down)
    


12
45 60 82 72 65 32 53 84 103 110 89 95
3 2


In [7]:
r1=int(input())
c1=int(input())
matrix1=[]
for i in range(r1):
    matrix1.append(list(map(int,input().split())))
r2=int(input())
c2=int(input())
matrix2=[]
for i in range(r2):
    matrix2.append(list(map(int,input().split())))
C=int(input())
m2=[[matrix2[j][i] for j in range(len(matrix2[i]))] for i in range(len(matrix2))]
matrix3=[]

for i in range(r1):
    row=[]
    for j in range(c1):
        count=0
        for x in list(zip(matrix1[i],m2[j])):
            if sum(x)<=C:
                count+=1
        row.append(count)
    matrix3.append(row)

for k in matrix3:
    for l in k:
        print(l,end='\t')
    print()
                                        

3
4
4
4
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [8]:
print(list(zip([1,2,3],[4,5,6])))

[(1, 4), (2, 5), (3, 6)]


In [12]:
S=input()
n=int(input())
lst=[]
for i in range(len(S)):
    for j in range(i,len(S)):
        lst.append(S[i:j+1])

L=[]
for i in lst:
    if len(i)==n:
        L.append(i)
for ele in L:
    ans=True
    for j in ele:
        if j in 'aeiou':
            ans=False
            break
    if ans==True:
        print(ele)

apple
3
ppl


In [1]:
17^59

42

In [3]:
29^67

94

In [7]:
from functools import reduce
a=[1,2,3]
b=[4,5,6]
print(list(map(lambda x,y:x^y,a,b)))

[5, 7, 5]


In [ ]:
n=int(input())
lst=list(map(int,input().split()))


In [10]:
n=int(input())
lst=list(map(int,input().split()))
common=[]
lst.sort()

for i in range(1,lst[0]+1):
    ans=True
    for j in lst:
        if j%i!=0:
            ans=False
            break
    if ans==True:
        common.append(i)
            
    
if len(common)==1 and 1 in common:
    print('NO')
else:
    print('YES')

    

3
2 3 4
NO
[1]


In [17]:
import itertools
area=int(input())
lst=[i for i in range(1,area+1) if area%i==0]
L=list(itertools.combinations(lst,2))
L1=[(i,j) for i,j in L if i*j==area]
print(len(L1))
print(L1)

36
4
[(1, 36), (2, 18), (3, 12), (4, 9)]


In [19]:
import string
import textwrap
lst=list(string.ascii_letters)
for i in range(len(lst)):
    if lst[i] in 'abcdefghijklmnopqrstuvwxyz':
        lst[i]=chr(ord(lst[i])-32)
    else:
        lst[i]=chr(ord(lst[i])+32)

s=input()
w=input()

l=textwrap.wrap(s,2)


if len(s)!=(2*len(w)):
    print(-1)
else: 
            
    c=0
    for i in range(len(w)):
        if lst.index(w[i])+1==int(l[i]):
            c+=1
    print(c)
    

234501
WsA
3
